In [3]:
import pandas as pd
# xls=pd.ExcelFile(r'E:\resource\scientific resource\Projects\writing style\plos_ethnea_new.xlsx')
# df = xls.parse("final")
# df.head()
# gender_df=pd.read_csv(r"E:\resource\scientific resource\Projects\writing style\paper three-g+i+w\plos_ethnea.tsv", sep='\t')
# pmdoi_df=pd.read_csv(r"E:\resource\scientific resource\Projects\writing style\paper three-g+i+w\doi_pmid.txt", sep='\t',names=['pmid','doi'])
# result = gender_df.join(pmdoi_df, how='inner')
# result.head()
# result = result[result.d != 0]

group_df  = pd.read_excel(r'E:\resource\scientific resource\Projects\writing style\paper one-writing style\data\writing style final.xlsx',sheetname=0)

,doi,group,nl,vl,jl,fl,voca,that,which,sl,sstd,nr,vr,jr,fr
0,10.1371/journal.pbio.0000001,2.5,6.93,6.72,7.30,6.49,1599,103,1,34.34,15.22,0.36,0.13,0.07,0.03
1,10.1371/journal.pbio.0000002,2.5,7.02,6.97,6.85,6.84,756,12,1,27.22,14.42,0.37,0.16,0.08,0.03
2,10.1371/journal.pbio.0000005,1.5,6.86,7.03,7.63,7.21,2137,75,19,29.52,11.99,0.36,0.13,0.08,0.03
3,10.1371/journal.pbio.0000006,2.5,7.25,6.56,6.56,5.71,941,21,2,35.94,29.76,0.40,0.11,0.08,0.02
4,10.1371/journal.pbio.0000008,1.0,6.83,5.83,6.90,6.23,1367,51,0,26.92,17.95,0.36,0.17,0.09,0.05

In [8]:
gender_df=pd.read_excel(r"E:\resource\scientific resource\Projects\writing style\paper three-g+i+w\joined_result.xlsx",sheetname=0)
gender_df=gender_df[['au_order','genni','doi']]
gender_df.head()

   au_order genni                                                doi
0         1     F  10.1371/annotation/008b05a8-229b-4aca-94ae-91e...
1         1     F  10.1371/annotation/010f6c7f-9745-4810-a370-c96...
2         1     F  10.1371/annotation/01406b4d-7869-4e7f-b294-433...
3         5     F  10.1371/annotation/020848d7-0453-42df-bf94-40e...
4         1     F  10.1371/annotation/02369930-29de-4cd6-a059-952...
5        10     F  10.1371/annotation/024a206e-293f-4a95-a188-783...
6         1     F  10.1371/annotation/0263ccf5-239b-48d7-8880-5f4...
7        10     F  10.1371/annotation/029c403b-10aa-47af-9e99-114...
8        12     F  10.1371/annotation/03280dea-66ce-4ba6-8ac5-f98...
9         1     F  10.1371/annotation/03304989-b70c-400c-b752-2e3...

In [25]:
gender_df1 = gender_df[gender_df['au_order']==1]
gender_dfc = gender_df[gender_df['au_order']>1]
gender_dfc=gender_dfc.rename(columns = {'genni':'gennic',"au_order":"orderc"})
new_gender=pd.merge(gender_df1, gender_dfc, on=['doi'])
new_gender.size

0